// ============================================================
// BAYSHIELD -- Data Models, Types & Seed Data
// ============================================================

export type ThreatLevel = 'monitoring' | 'advisory' | 'warning' | 'critical';
export type AgentStatus = 'idle' | 'active' | 'processing' | 'complete' | 'error';
export type IncidentActionStatus = 'new' | 'reviewed' | 'assigned' | 'completed';

export interface WeatherData {
  stormName: string;
  category: number;
  windSpeed: number;
  pressure: number;
  lat: number;
  lng: number;
  movement: string;
  landfall: string;
  threatLevel: ThreatLevel;
  radarReturns: number;
  surgeHeight: number;
}

export interface VulnerabilityZone {
  id: string;
  name: string;
  floodZone: 'A' | 'AE' | 'VE' | 'X';
  population: number;
  elderlyPct: number;
  lowIncomePct: number;
  mobilityImpairedPct: number;
  riskScore: number;
  lat: number;
  lng: number;
  status: 'safe' | 'watch' | 'warning' | 'evacuate';
}

export interface Resource {
  id: string;
  type: 'shelter' | 'supply_depot' | 'medical' | 'evacuation_route';
  name: string;
  capacity: number;
  currentOccupancy: number;
  status: 'available' | 'filling' | 'full' | 'closed';
  lat: number;
  lng: number;
  supplies?: string[];
}

export interface Alert {
  id: string;
  timestamp: Date;
  priority: 'info' | 'advisory' | 'warning' | 'critical';
  zone: string;
  message: string;
  agentSource?: string;
  actionRequired?: string;
  population?: number;
  type?: string;
  source?: string;
}

export interface AgentMessage {
  id: string;
  from: string;
  to: string;
  timestamp: Date;
  type: 'data' | 'request' | 'response' | 'alert';
  eventType: string;
  payload: string;
  content: string;
  status: 'sent' | 'received' | 'processing' | 'acknowledged' | 'delivered';
}

export interface AgentState {
  id: string;
  name: string;
  role: string;
  status: AgentStatus;
  lastAction: string;
  loopCount: number;
  confidence: number;
  processingTime: number;
  color: string;
  glowClass: string;
  icon: string;
}

// NEW: ActionPlan -- generated by Alert Commander
export interface ActionPlan {
  id: string;
  title: string;
  summary: string;
  recommendations: string[];
  createdAt: Date;
  severity: ThreatLevel;
  zonesAffected: string[];
  populationCovered: number;
  agentSource: string;
}

export interface IncidentAction {
  id: string;
  planId: string;
  title: string;
  detail: string;
  severity: ThreatLevel;
  status: IncidentActionStatus;
  owner: string | null;
  managedBy?: 'system' | 'operator';
  createdAt: Date;
  updatedAt: Date;
  dueLabel: string;
  zonesAffected: string[];
  populationCovered: number;
  source: string;
  recommendations: string[];
}

// NEW: InfrastructurePrediction -- predictive model output
export interface InfrastructurePrediction {
  id: string;
  alertId: string;
  timeframe: string;
  powerOutagePct: number;
  roadClosurePct: number;
  hospitalRisk: 'low' | 'moderate' | 'high' | 'critical';
  damageEstimate: string;
  recoveryDays: number;
  floodDepthFt: number;
  windDamageRisk: 'low' | 'moderate' | 'high' | 'extreme';
}

