import {
  int, mysqlEnum, mysqlTable, text, timestamp,
  varchar, bigint, float, tinyint, json, uniqueIndex
} from "drizzle-orm/mysql-core";

/**
 * Core user table backing auth flow.
 */
export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(),
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

// ── BayShield Domain Tables ──────────────────────────────────────────────────

/**
 * Agent pipeline runs — one record per full 4-agent execution.
 */
export const agentRuns = mysqlTable("agent_runs", {
  id: int("id").autoincrement().primaryKey(),
  runId: varchar("runId", { length: 64 }).notNull().unique(),
  mode: mysqlEnum("mode", ["live", "simulation"]).default("live").notNull(),
  threatLevel: varchar("threatLevel", { length: 32 }).notNull(),
  totalAtRisk: int("totalAtRisk").default(0).notNull(),
  selfCorrectionApplied: tinyint("selfCorrectionApplied").default(0).notNull(),
  correctionDetails: text("correctionDetails"),
  completedAt: timestamp("completedAt").defaultNow().notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type AgentRun = typeof agentRuns.$inferSelect;
export type InsertAgentRun = typeof agentRuns.$inferInsert;

/**
 * A2A messages exchanged between agents during a pipeline run.
 */
export const agentMessages = mysqlTable("agent_messages", {
  id: int("id").autoincrement().primaryKey(),
  messageId: varchar("messageId", { length: 64 }).notNull().unique(),
  runId: varchar("runId", { length: 64 }).notNull(),
  fromAgent: varchar("fromAgent", { length: 64 }).notNull(),
  toAgent: varchar("toAgent", { length: 64 }).notNull(),
  eventType: varchar("eventType", { length: 32 }).notNull(),
  content: text("content").notNull(),
  payload: text("payload"),
  timestamp: timestamp("timestamp").defaultNow().notNull(),
});

export type AgentMessage = typeof agentMessages.$inferSelect;
export type InsertAgentMessage = typeof agentMessages.$inferInsert;

/**
 * Action plans generated by the Alert Commander.
 */
export const actionPlans = mysqlTable("action_plans", {
  id: int("id").autoincrement().primaryKey(),
  planId: varchar("planId", { length: 64 }).notNull().unique(),
  runId: varchar("runId", { length: 64 }).notNull(),
  title: varchar("title", { length: 256 }).notNull(),
  priority: int("priority").notNull(),
  action: text("action").notNull(),
  shelter: varchar("shelter", { length: 256 }),
  route: varchar("route", { length: 512 }),
  population: int("population").default(0),
  rationale: text("rationale"),
  outputType: varchar("outputType", { length: 32 }).default("deterministic"),
  correctionApplied: tinyint("correctionApplied").default(0),
  llmExplanation: text("llmExplanation"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type ActionPlan = typeof actionPlans.$inferSelect;
export type InsertActionPlan = typeof actionPlans.$inferInsert;

export const incidentActionState = mysqlTable("incident_action_state", {
  id: int("id").autoincrement().primaryKey(),
  actionKey: varchar("actionKey", { length: 128 }).notNull(),
  mode: mysqlEnum("mode", ["live", "simulation"]).default("live").notNull(),
  planId: varchar("planId", { length: 64 }).notNull(),
  title: varchar("title", { length: 256 }).notNull(),
  status: mysqlEnum("status", ["new", "reviewed", "assigned", "completed"]).default("new").notNull(),
  owner: varchar("owner", { length: 128 }),
  source: varchar("source", { length: 64 }).default("Alert Commander"),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
}, (table) => ({
  actionKeyUnique: uniqueIndex("incident_action_state_action_key_uq").on(table.actionKey),
}));

export type IncidentActionState = typeof incidentActionState.$inferSelect;
export type InsertIncidentActionState = typeof incidentActionState.$inferInsert;

export const incidentDispatches = mysqlTable("incident_dispatches", {
  id: int("id").autoincrement().primaryKey(),
  dispatchKey: varchar("dispatchKey", { length: 128 }).notNull(),
  actionKey: varchar("actionKey", { length: 128 }).notNull(),
  mode: mysqlEnum("mode", ["live", "simulation"]).default("live").notNull(),
  channel: varchar("channel", { length: 64 }).notNull(),
  target: varchar("target", { length: 128 }).notNull(),
  status: mysqlEnum("status", ["pending", "delivered", "local_only", "acknowledged"]).default("pending").notNull(),
  detail: text("detail"),
  acknowledgedAt: timestamp("acknowledgedAt"),
  acknowledgedBy: varchar("acknowledgedBy", { length: 128 }),
  lastAttemptAt: timestamp("lastAttemptAt"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
}, (table) => ({
  dispatchKeyUnique: uniqueIndex("incident_dispatches_dispatch_key_uq").on(table.dispatchKey),
}));

export type IncidentDispatch = typeof incidentDispatches.$inferSelect;
export type InsertIncidentDispatch = typeof incidentDispatches.$inferInsert;

export const incidentAuditLog = mysqlTable("incident_audit_log", {
  id: int("id").autoincrement().primaryKey(),
  eventKey: varchar("eventKey", { length: 128 }).notNull(),
  actionKey: varchar("actionKey", { length: 128 }).notNull(),
  mode: mysqlEnum("mode", ["live", "simulation"]).default("live").notNull(),
  eventType: varchar("eventType", { length: 64 }).notNull(),
  actor: varchar("actor", { length: 128 }).notNull(),
  summary: text("summary").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
}, (table) => ({
  eventKeyUnique: uniqueIndex("incident_audit_log_event_key_uq").on(table.eventKey),
}));

export type IncidentAuditLog = typeof incidentAuditLog.$inferSelect;
export type InsertIncidentAuditLog = typeof incidentAuditLog.$inferInsert;

/**
 * Weather snapshots from KTPA station observations.
 */
export const weatherSnapshots = mysqlTable("weather_snapshots", {
  id: int("id").autoincrement().primaryKey(),
  station: varchar("station", { length: 16 }).default("KTPA").notNull(),
  temperatureC: float("temperatureC"),
  windSpeedMs: float("windSpeedMs"),
  windDirection: varchar("windDirection", { length: 8 }),
  pressurePa: float("pressurePa"),
  description: varchar("description", { length: 256 }),
  threatLevel: varchar("threatLevel", { length: 32 }),
  alertCount: int("alertCount").default(0),
  stormCount: int("stormCount").default(0),
  observedAt: timestamp("observedAt").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type WeatherSnapshot = typeof weatherSnapshots.$inferSelect;
export type InsertWeatherSnapshot = typeof weatherSnapshots.$inferInsert;

/**
 * Vulnerability zone assessments per pipeline run.
 */
export const vulnerabilityZones = mysqlTable("vulnerability_zones", {
  id: int("id").autoincrement().primaryKey(),
  runId: varchar("runId", { length: 64 }).notNull(),
  zoneId: varchar("zoneId", { length: 32 }).notNull(),
  name: varchar("name", { length: 128 }).notNull(),
  floodZone: varchar("floodZone", { length: 8 }).notNull(),
  riskScore: int("riskScore").notNull(),
  population: int("population").notNull(),
  status: varchar("status", { length: 32 }).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type VulnerabilityZone = typeof vulnerabilityZones.$inferSelect;
export type InsertVulnerabilityZone = typeof vulnerabilityZones.$inferInsert;

/**
 * Shelter status per pipeline run.
 */
export const shelterStatus = mysqlTable("shelter_status", {
  id: int("id").autoincrement().primaryKey(),
  runId: varchar("runId", { length: 64 }).notNull(),
  shelterId: varchar("shelterId", { length: 32 }).notNull(),
  name: varchar("name", { length: 128 }).notNull(),
  capacity: int("capacity").notNull(),
  currentOccupancy: int("currentOccupancy").default(0),
  status: varchar("status", { length: 32 }).default("open"),
  source: varchar("source", { length: 64 }).default("estimated"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type ShelterStatusRecord = typeof shelterStatus.$inferSelect;
export type InsertShelterStatus = typeof shelterStatus.$inferInsert;

/**
 * Hurricane / storm simulations created by users via the Simulation Studio.
 * Each record stores the full track, parameters, and LLM-generated analysis.
 */
export const stormSimulations = mysqlTable("storm_simulations", {
  id: int("id").autoincrement().primaryKey(),
  simId: varchar("simId", { length: 64 }).notNull().unique(),
  name: varchar("name", { length: 128 }).notNull(),
  stormType: mysqlEnum("stormType", ["hurricane", "tropical_storm", "tropical_depression", "tornado", "flood", "nor_easter"]).default("hurricane").notNull(),
  category: int("category").default(1),            // Saffir-Simpson 1-5 (null for non-hurricanes)
  windSpeedKph: int("windSpeedKph").default(150),
  radiusKm: int("radiusKm").default(80),            // radius of maximum winds
  forwardSpeedKph: int("forwardSpeedKph").default(20),
  track: json("track").notNull(),                   // Array of {lat, lng, timestamp?} waypoints
  landfall: json("landfall"),                       // {lat, lng} of projected landfall point
  // LLM-generated analysis (stored as structured JSON)
  analysis: json("analysis"),                       // full structured impact analysis
  analysisText: text("analysisText"),               // raw markdown from LLM
  affectedPopulation: int("affectedPopulation").default(0),
  status: mysqlEnum("status", ["pending", "analyzing", "complete", "error"]).default("pending").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type StormSimulation = typeof stormSimulations.$inferSelect;
export type InsertStormSimulation = typeof stormSimulations.$inferInsert;
